#!/usr/bin/env node
/**
 * Refreshes src/data/timetables.gen.mjs from the tracker's own timetable log.
 *
 *   TRACKER_SSH=ubuntu@<vm> npm run timetables
 *
 * Copies export-on-vm.cjs to the VM, runs it under `nice` against the tracker database, and
 * writes the result here as a plain ES module so that Astro and the Node build scripts can both
 * import it without a JSON loader. The host is taken from the environment rather than written
 * down, because this repository is public.
 *
 * The build never runs this — Cloudflare Pages cannot reach the VM. Run it by hand, check the
 * diff, and commit the regenerated file; the pages only change when that file does.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TIMETABLE_PAIRS } from '../../src/data/pages.data.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../src/data/timetables.gen.mjs');
const HOST = process.env.TRACKER_SSH;
const KEY = process.env.TRACKER_SSH_KEY || path.join(os.homedir(), '.ssh/st-tracker-deploy');

if (!HOST) {
  console.error('Set TRACKER_SSH=<user>@<tracker vm> (see deploy/README.md).');
  process.exit(1);
}

const ssh = ['-i', KEY, '-o', 'BatchMode=yes', '-o', 'ConnectTimeout=20'];
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'timetables-'));
const pairsFile = path.join(tmp, 'pairs.json');
fs.writeFileSync(pairsFile, JSON.stringify(TIMETABLE_PAIRS));

execFileSync('scp', ['-q', ...ssh, path.join(HERE, 'export-on-vm.cjs'), pairsFile, `${HOST}:/tmp/`]);
const raw = execFileSync('ssh', [...ssh, HOST,
  'timeout 300 nice -n 19 node --no-warnings /tmp/export-on-vm.cjs /tmp/pairs.json; rm -f /tmp/export-on-vm.cjs /tmp/pairs.json'],
{ maxBuffer: 64 * 1024 * 1024 }).toString();
const data = JSON.parse(raw);

const found = Object.keys(data.pairs).length;
// One service per line, so a refresh reads as a diff of timings rather than one changed line.
const body = Object.entries(data.pairs).map(([key, { services, ...pair }]) => [
  `  ${JSON.stringify(key)}: { ${Object.entries(pair).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join(', ')}, services: [`,
  ...services.map((s) => `    ${JSON.stringify(s)},`),
  '  ] },',
].join('\n')).join('\n');

fs.writeFileSync(OUT, `/**
 * GENERATED by scripts/timetables/pull.mjs — do not edit by hand; re-run it instead.
 *
 * Departures GSRTC returned to real rider searches on ST Tracker, merged across up to 40 recent
 * searches per direction. Keyed "<fromStationId>><toStationId>". ${found} of ${TIMETABLE_PAIRS.length} directions had data.
 */
export default { generatedAt: ${JSON.stringify(data.generatedAt)}, pairs: {
${body}
} };
`);
console.log(`${found}/${TIMETABLE_PAIRS.length} directions with data -> ${path.relative(process.cwd(), OUT)}`);
