#!/usr/bin/env node
/**
 * Refreshes src/data/hubs.gen.mjs: for every bus stand with a city page, the destinations riders
 * search most from it, and GSRTC's departures to each, from the tracker's own timetable log.
 *
 *   TRACKER_SSH=ubuntu@<vm> npm run hubs
 *
 * Two read-only steps on the VM, both under `nice` and a timeout: discover-on-vm.cjs counts
 * searches per destination on the (from_id, to_id) index, then export-on-vm.cjs (the route
 * pages' exporter) reads the departures for the chosen pairs. Like pull.mjs, the build never
 * runs this: run it by hand, check the diff, commit the regenerated file.
 *
 * Destination names come from GSRTC's own station list (scripts/seed-stations.json in the
 * tracker repo, TRACKER_REPO), or from CITY when the site already names that station.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CITY, CITY_ROUTES } from '../../src/data/pages.data.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '../../src/data/hubs.gen.mjs');
const HOST = process.env.TRACKER_SSH;
const KEY = process.env.TRACKER_SSH_KEY || path.join(os.homedir(), '.ssh/st-tracker-deploy');
const SEED = path.join(process.env.TRACKER_REPO || path.join(os.homedir(), 'ST-Tracker'), 'scripts/seed-stations.json');
/** At most this many destinations per bus stand, and only ones searched at least MIN_SEARCHES times. */
const MAX_DESTINATIONS = 10;
const MIN_SEARCHES = 3;

if (!HOST) { console.error('Set TRACKER_SSH=<user>@<tracker vm> (see deploy/README.md).'); process.exit(1); }
if (!fs.existsSync(SEED)) { console.error(`Station list not found at ${SEED}; set TRACKER_REPO.`); process.exit(1); }

const seed = JSON.parse(fs.readFileSync(SEED, 'utf8'));
const stations = new Map((Array.isArray(seed) ? seed : Object.values(seed)).map((s) => [Number(s.StationId), s]));
const byId = new Map(Object.values(CITY).map((c) => [c.id, c]));
const nameOf = (id) => byId.get(id)?.name || stations.get(id)?.StationName || null;
const gujOf = (id) => byId.get(id)?.guj || stations.get(id)?.StationNameGuj || '';

const ssh = ['-i', KEY, '-o', 'BatchMode=yes', '-o', 'ConnectTimeout=20', '-o', 'ServerAliveInterval=10', '-o', 'ServerAliveCountMax=3'];
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'hubs-'));
const run = (script, input, env = '') => {
  const file = path.join(tmp, path.basename(input.name));
  fs.writeFileSync(file, JSON.stringify(input.data));
  execFileSync('scp', ['-q', ...ssh, path.join(HERE, script), file, `${HOST}:/tmp/`], { timeout: 60_000 });
  const out = execFileSync('ssh', [...ssh, HOST,
    `${env} timeout 300 nice -n 19 node --no-warnings /tmp/${script} /tmp/${path.basename(file)}; rm -f /tmp/${script} /tmp/${path.basename(file)}`],
  { maxBuffer: 128 * 1024 * 1024, timeout: 330_000 }).toString();
  return JSON.parse(out);
};

const origins = Object.keys(CITY_ROUTES).map((k) => CITY[k].id);
const found = run('discover-on-vm.cjs', { name: 'origins.json', data: origins }, 'TOP=16');

const hubs = {};
const pairs = [];
for (const [origin, list] of Object.entries(found.origins)) {
  const keep = list.filter(([to, n]) => n >= MIN_SEARCHES && to !== Number(origin) && nameOf(to)).slice(0, MAX_DESTINATIONS);
  hubs[origin] = keep.map(([to, n]) => [to, n, nameOf(to), gujOf(to)]);
  for (const [to] of keep) pairs.push([Number(origin), to]);
}
const exported = run('export-on-vm.cjs', { name: 'pairs.json', data: pairs }, 'MAX_SNAPSHOTS=15');

const body = Object.entries(exported.pairs).map(([key, { services, ...pair }]) => [
  `  ${JSON.stringify(key)}: { ${Object.entries(pair).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join(', ')}, services: [`,
  ...services.map((s) => `    ${JSON.stringify(s)},`),
  '  ] },',
].join('\n')).join('\n');

fs.writeFileSync(OUT, `/**
 * GENERATED by scripts/timetables/pull-hubs.mjs — do not edit by hand; re-run it instead.
 *
 * For each bus stand with a city page: the destinations riders searched most from it on ST
 * Tracker in the last three weeks ([stationId, searches, name, gujarati]), and GSRTC's
 * departures to each, merged across up to 15 recent searches per direction.
 * ${Object.keys(exported.pairs).length} of ${pairs.length} directions had data.
 */
export default { generatedAt: ${JSON.stringify(exported.generatedAt)}, hubs: ${JSON.stringify(hubs)}, pairs: {
${body}
} };
`);
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`${Object.keys(hubs).length} bus stands, ${pairs.length} directions asked, ${Object.keys(exported.pairs).length} with data -> ${path.relative(process.cwd(), OUT)}`);
